import type { NextPage } from 'next'
import Head from 'next/head'
// import Image from 'next/image'
import { Provider } from '@self.id/framework'
import styles from '../styles/Home.module.css'
import ConnectButton from '../components/ConnectButton'

const Home: NextPage = () => {
  return (
    <> 
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <Provider client={{ ceramic: 'testnet-clay' }}>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Hashchat
        </h1>
        <ConnectButton/>
      </main>
      </Provider>
    </>
  )
}

export default Home